# Uncomment the next line to define a global platform for your project
 platform :ios, '13.1'

target 'wificaresp8266' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for wificaresp8266
	pod 'Alamofire', '~> 5.0.0-rc.2'
end
